export const serbianMunicipalities = [
  'Ada', 'Aleksandrovac', 'Aleksinac', 'Alibunar', 'Apatin', 'Aranđelovac', 'Arilje',
  'Babušnica', 'Bajina Bašta', 'Batočina', 'Bač', 'Bačka Palanka', 'Bačka Topola', 'Bački Petrovac',
  'Bela Crkva', 'Bela Palanka', 'Beočin', 'Bečej', 'Blace', 'Bogatić', 'Bojnik', 'Boljevac', 'Bor',
  'Bosilegrad', 'Brus', 'Bujanovac',
  'Valjevo', 'Varvarin', 'Velika Plana', 'Veliko Gradište', 'Vladičin Han', 'Vladimirci', 'Vlasotince',
  'Voždovac', 'Vračar', 'Vranje', 'Vrnjačka Banja', 'Vršac',
  'Gadžin Han', 'Golubac', 'Gornji Milanovac', 'Grocka',
  'Despotovac', 'Dimitrovgrad', 'Doljevac',
  'Žabalj', 'Žabari', 'Žagubica', 'Žitište', 'Žitorađa',
  'Zaječar', 'Zemun', 'Zrenjanin', 'Zvezdara', 'Zvečan',
  'Ivanjica', 'Inđija', 'Irig',
  'Jagodina',
  'Kanjiža', 'Kikinda', 'Kladovo', 'Knić', 'Knjaževac', 'Koceljeva', 'Kosjerić',
  'Kovačica', 'Kovin', 'Kragujevac', 'Kraljevo', 'Krupanj', 'Kruševac', 'Kula', 'Kuršumlija', 'Kučevo',
  'Lazarevac', 'Lapovo', 'Lebane', 'Leskovac', 'Loznica', 'Lučani', 'Ljig', 'Ljubovija',
  'Majdanpek', 'Mali Iđoš', 'Mali Zvornik', 'Malo Crniće', 'Medveđa', 'Merošina', 'Mionica',
  'Mladenovac',
  'Negotin', 'Niš', 'Niška Banja', 'Nova Crnja', 'Nova Varoš', 'Novi Bečej', 'Novi Kneževac',
  'Novi Pazar', 'Novi Sad', 'Novo Brdo',
  'Obrenovac', 'Opovo', 'Osečina',
  'Palilula', 'Pančevo', 'Paraćin', 'Pećinci', 'Petrovac na Mlavi', 'Pirot', 'Plandište',
  'Požarevac', 'Požega', 'Preševo', 'Priboj', 'Prijepolje', 'Prokuplje',
  'Ražanj', 'Raška', 'Rača', 'Rekovac', 'Ruma',
  'Savski venac', 'Senta', 'Sečanj', 'Sjenica', 'Smederevo', 'Smederevska Palanka',
  'Sokobanja', 'Sombor', 'Sopot', 'Srbobran', 'Sremska Mitrovica', 'Sremski Karlovci',
  'Stara Pazova', 'Stari grad', 'Subotica', 'Surdulica', 'Surčin', 'Svilajnac', 'Svrljig',
  'Temerin', 'Titel', 'Topola', 'Trgovište', 'Trstenik', 'Tutin',
  'Ub', 'Užice',
  'Čajetina', 'Čačak', 'Čoka', 'Čukarica',
  'Šabac', 'Šid', 'Štimlje', 'Štrpce',
  'Beograd', 'Niš', 'Novi Sad', 'Kragujevac',
].sort()

export const serbianCities = serbianMunicipalities
